version: '3.7'

services:

  # Postgres latest
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Documents/Docker/postgres/postgresql:/var/lib/postgresql/data


  # pgadmin4 latest
  pgadmin4:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: lavergne.remy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - $HOME/Documents/Docker/postgres/pgadmin:/etc/pgadmin
      - $HOME/Documents/Docker/postgres/lib/pgadmin:/var/lib/pgadmin